dist: xenial
# os: osx
language: minimal
install: skip

rvm:
- 2.6.5
# - 2.6.6
# - 2.7.0
# - 2.7.1

script:
# - export TRAVIS_AGENT_DEBUG=true
- uname -a
- ruby -v
# - sleep 120
# - ssh -vv git@github.com
